<?xml version="1.0" encoding="utf-8"?><Database Name="ProductDB" Class="ProductDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=ProductDB;Integrated Security=True" SettingsObjectName="BusinessLayer.Properties.Settings" SettingsPropertyName="ProductDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Product" Member="Product">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ProductNums" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>